"""lineas de costo

Revision ID: 35e919f6cfc0
Revises: 2d55a3dba772
Create Date: 2026-09-14 19:20:35.530749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = '35e919f6cfc0'
down_revision: Union[str, Sequence[str], None] = '2d55a3dba772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('rubro', sa.String(length=20), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('cantidad', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('valor_calculado', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('advertencia', sa.Text(), nullable=True),
    sa.Column('valor_override', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('override_por', sa.String(length=120), nullable=True),
    sa.Column('override_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_de_corte.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_costo')
    # ### end Alembic commands ###
