"""formato: agregar disponible

Revision ID: 432d5c9cf8e2
Revises: 778ccf520cac
Create Date: 2026-09-14 12:34:50.175433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = '432d5c9cf8e2'
down_revision: Union[str, Sequence[str], None] = '778ccf520cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formatos', schema=None) as batch_op:
        # server_default para las filas que ya existan (si las hay): el
        # default de Python (`Formato.disponible = True`) solo aplica a
        # los INSERT nuevos, no completa columnas agregadas después.
        batch_op.add_column(
            sa.Column('disponible', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formatos', schema=None) as batch_op:
        batch_op.drop_column('disponible')

    # ### end Alembic commands ###
