"""catalogo real, trabajos y grupos de corte multi-material

Revision ID: 778ccf520cac
Revises: 
Create Date: 2026-09-11 18:24:41.213889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = '778ccf520cac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones_moneda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('valor_a_ars', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda', 'fecha', name='uq_cotizacion_moneda_fecha')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('espesor', sa.String(length=40), nullable=True),
    sa.Column('nesteable_por_area', sa.Boolean(), nullable=False),
    sa.Column('provisto_por_cliente', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'espesor', name='uq_material_nombre_espesor')
    )
    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('archivo_origen', sa.String(length=260), nullable=True),
    sa.Column('archivo_guardado', sa.String(length=400), nullable=True),
    sa.Column('escala_a_mm', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('ancho_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('alto_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('es_retazo', sa.Boolean(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('precio_compra', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('iva_pct', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('unidad_compra', sa.String(length=20), nullable=True),
    sa.Column('unidad_venta', sa.String(length=20), nullable=True),
    sa.Column('factor_conversion', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('costo_unidad_venta', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametros_corte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('kerf_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('margen_borde_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('separacion_piezas_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('rotaciones_permitidas', sa.String(length=20), nullable=False),
    sa.Column('confirmado_con_taller', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('grupos_de_corte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('formato_id', sa.Integer(), nullable=True),
    sa.Column('parametros_usados', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formato_id'], ['formatos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejecuciones_nesting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('motor', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('semilla', sa.String(length=80), nullable=True),
    sa.Column('opciones', sa.JSON(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('planchas_usadas', sa.Integer(), nullable=True),
    sa.Column('aprovechamiento_pct', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('largo_corte_compartido_mm', app.modelos.tipos.Milimetros(length=40), nullable=True),
    sa.Column('milisegundos', sa.Integer(), nullable=True),
    sa.Column('mensajes', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('es_definitiva', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_de_corte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('id_origen', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('ancho_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('alto_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('contorno_mm', sa.JSON(), nullable=False),
    sa.Column('agujeros_mm', sa.JSON(), nullable=False),
    sa.Column('descartada', sa.Boolean(), nullable=False),
    sa.Column('contorno_recto', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_de_corte.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colocaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('instancia', sa.Integer(), nullable=False),
    sa.Column('plancha_indice', sa.Integer(), nullable=False),
    sa.Column('centro_x_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('centro_y_mm', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('angulo_grados', app.modelos.tipos.Milimetros(length=40), nullable=False),
    sa.Column('movida_a_mano', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_nesting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colocaciones')
    op.drop_table('piezas')
    op.drop_table('ejecuciones_nesting')
    op.drop_table('grupos_de_corte')
    op.drop_table('parametros_corte')
    op.drop_table('formatos')
    op.drop_table('trabajos')
    op.drop_table('materiales')
    op.drop_table('cotizaciones_moneda')
    # ### end Alembic commands ###
