"""ejecucion_id en linea de costo

Revision ID: faf932c99ef5
Revises: fbe481362a57
Create Date: 2026-09-14 20:54:24.681023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = 'faf932c99ef5'
down_revision: Union[str, Sequence[str], None] = 'fbe481362a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas_costo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ejecucion_id', sa.Integer(), nullable=True))
        # El modo batch de SQLite recrea la tabla entera y necesita el
        # nombre explícito del constraint (autogenerate lo deja en
        # `None`, que solo funciona en Postgres).
        batch_op.create_foreign_key(
            'fk_lineas_costo_ejecucion_id', 'ejecuciones_nesting', ['ejecucion_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas_costo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lineas_costo_ejecucion_id', type_='foreignkey')
        batch_op.drop_column('ejecucion_id')

    # ### end Alembic commands ###
