"""margen, iva y moneda por linea

Revision ID: fbe481362a57
Revises: 35e919f6cfc0
Create Date: 2026-09-14 20:35:11.695310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = 'fbe481362a57'
down_revision: Union[str, Sequence[str], None] = '35e919f6cfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas_costo', schema=None) as batch_op:
        # server_default para las filas que ya existan (si las hay): el
        # default de Python ("ARS") solo aplica a los INSERT nuevos.
        batch_op.add_column(
            sa.Column('moneda', sa.String(length=3), nullable=False, server_default='ARS')
        )

    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margen_pct', app.modelos.tipos.Milimetros(length=40), nullable=True))
        batch_op.add_column(sa.Column('iva_pct', app.modelos.tipos.Milimetros(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_column('iva_pct')
        batch_op.drop_column('margen_pct')

    with op.batch_alter_table('lineas_costo', schema=None) as batch_op:
        batch_op.drop_column('moneda')

    # ### end Alembic commands ###
