"""formato: agregar precio_simulado

Revision ID: ff9dc9b0dcdf
Revises: faf932c99ef5
Create Date: 2026-09-22 20:19:56.372136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Los tipos propios (Milimetros) aparecen por nombre completo en las
# migraciones autogeneradas; sin este import, `upgrade` falla con
# NameError. Va en la plantilla para que valga para todas.
import app.modelos.tipos


# revision identifiers, used by Alembic.
revision: str = 'ff9dc9b0dcdf'
down_revision: Union[str, Sequence[str], None] = 'faf932c99ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formatos', schema=None) as batch_op:
        # server_default para las filas que ya existan: el default de
        # Python (`Formato.precio_simulado = False`) solo aplica a los
        # INSERT nuevos, no completa columnas agregadas después.
        batch_op.add_column(
            sa.Column('precio_simulado', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formatos', schema=None) as batch_op:
        batch_op.drop_column('precio_simulado')

    # ### end Alembic commands ###
